### ISSUE TITLE
Segregated/Modular Install

### ISSUE THREAD

**Issue by rjhilgefort** [jacobtomlinson/carte-noire#15]
It'll probably be a bit of work/restructuring, but would be nice if this could be installed overtop an existing Jekyll project more easily as a submodule.

I currently have it installed as a submodule with the assets symlink'd to the root directory of my project.

**Comment by jacobtomlinson** [comment]
That sounds sensible. I haven't used Jekyll in that way before. 

Do you have a link to your repository so I can see how you've structured it?

**Comment by jacobtomlinson** [comment]
This seems to just be sitting here with no response. I'll give you another week to reply and then close it.

**Comment by rjhilgefort** [comment]
I have content currently committed to the private repo I was referring to. I'll see about recreating it in a public repo on Github. I'm not in love with the approach either- I think it's more of a Jekyll feature anyhow. Feel free to close and I can reopen later.

**Comment by jacobtomlinson** [comment]
No problem.

**Comment by jacobtomlinson** [comment]
I think this is coming in jekyll 3. I'll re-open when it's out.
