### ISSUE TITLE
no css shown

### ISSUE THREAD

**Issue by llcc** [jacobtomlinson/carte-noire#17]
@jacobtomlinson 

Thanks for your template.
I downloaded your files and push it to my repository. But it seems like that there is something wrong of the css, like:
![image](https://cloud.githubusercontent.com/assets/3996879/8396901/997fda90-1df4-11e5-854b-041d46869616.png)
Here is my link: llcc.github.io/layatjpy/

Thanks if you can give me some help.

**Comment by jacobtomlinson** [comment]
It looks like the css isn't loading as you said. however I can't reproduce it. Are you still having this problem?

![image](https://cloud.githubusercontent.com/assets/1610850/8506806/484338f0-221f-11e5-999f-548ba37488ad.png)

**Comment by llcc** [comment]
@jacobtomlinson  Sorry for append late.
There was something with the css and js path, and I solved it at last. Thanks!

**Comment by jacobtomlinson** [comment]
Just for completeness in this issue it looks like you haven't set the base path in the settings. Hopefully you've sorted it though.

**Comment by jacobtomlinson** [comment]
You needed to set it here

https://github.com/llcc/layatjpy/blob/gh-pages/_config.yml#L5

You might want to undo your workaround and correct your configuration.

**Comment by radumas** [comment]
Just posting the jekyll gh-pages link here since I had the same issue and the fix was not immediately obvious to me

http://jekyllrb.com/docs/github-pages/
