### ISSUE TITLE
/posts/ vs /posts.html

### ISSUE THREAD

**Issue by ratulotron** [jacobtomlinson/carte-noire#18]
First of all, thanks for the awesome theme :smile: Although your in your blog it works when I click on All posts in the sidebar, the same doesn't work in my forked one. Surprisingly hen I tried to reach /posts.html it worked. How can I solve this?

See here: http://mnzr.me/posts/ doesn't work, but http://mnzr.me/posts.html works.

**Comment by jacobtomlinson** [comment]
Hi, thanks for your kind words

I think it might be to do with your `permalink` settings. Try changing it back to match mine and see if it fixes your issue.

https://github.com/mnzr/mnzr.github.io/blob/master/_config.yml#L31

**Comment by ratulotron** [comment]
Thank you very much! The problem got solved! :smile_cat:

**Comment by jacobtomlinson** [comment]
:+1:
