### ISSUE TITLE
Relative menu links

### ISSUE THREAD

**Issue by ssundarraj** [jacobtomlinson/carte-noire#19]
When I serve the blog on domain.tld/blog, the links in the menu on the left hand side don't work.

**Comment by jacobtomlinson** [comment]
Good spot! This is because the `{{ site.base_url }}` hasn't been used in that menu. This needs ot be corrected.

**Comment by ssundarraj** [comment]
Yeah. I fixed it when i deployed it. I shall send a PR soon.
