### ISSUE TITLE
Extending the links bar

### ISSUE THREAD

**Issue by pomeroyb** [jacobtomlinson/carte-noire#21]
I'm trying to add additional icons to the links bar (Namely fa-envelope for an email link), but the icon isn't showing up. This is the code I added to "_includes/header.html".

``` html
{% if site.email_link %}<a href="mailto:{{ site.email_link }}" target="_new"><i class="fa fa-envelope"></i></a>{% endif %}
```

I also added some colors to "style.scss".

``` css
$envelope:           #6dabda;
```

``` css
.fa-envelope:hover {
    color: $envelope;
}
```

My html code shows up in my published site's source, so I'm assuming that I'm missing some part of the css. Any hints?

Thanks for the great theme, by the way! :)

**Comment by jacobtomlinson** [comment]
I see you have successfully added it to the `mmenu` bar [here](https://github.com/pomeroyb/carte-noire/blob/gh-pages/_includes/header.html#L15). But you haven't added that line of HTML to the index page [here](https://github.com/pomeroyb/carte-noire/blob/gh-pages/index.html#L30), so it wont be displaying there.

![image](https://cloud.githubusercontent.com/assets/1610850/8794541/77892c36-2f7c-11e5-8225-4ec7039d73db.png)

**Comment by jacobtomlinson** [comment]
This has highlighted something I hadn't thought of though so I think I'll make an enhancement which means you only have to change it in one place. Thanks!

**Comment by pomeroyb** [comment]
Ah, thanks for that, didn't realize I was editing mmenu instead of the index's header. It works perfectly now. :+1:
