### ISSUE TITLE
Page build fails

### ISSUE THREAD

**Issue by gunhansancar** [jacobtomlinson/carte-noire#23]
hello,

I forked your theme and tried to edit one of the demo posts but after that it failed to build the page without giving the details.

I am new to the jekyll so what should I do? I don't want to install jekyll locally so,
I tried to fork jekyll-now theme and it works out of the box without installing anything, however it is not fancy as your theme. To use your theme should i install jekyll locally and then build and do something?

**Comment by jacobtomlinson** [comment]
I recommend you install jekyll locally and try building it there. You should get some better error messages then.

http://jekyllrb.com/docs/installation/

**Comment by gunhansancar** [comment]
I tried to avoid installing, but Installed anyway :)

Here is the message when I build locally

```
         ERROR: YOUR SITE COULD NOT BE BUILT:
                ------------------------------------
                Invalid date '{}': Post '_posts/2014-06-10-carte-noire-in-action.md' does not have a valid date in the YAML front matter.
```

Btw I just added one word to the post nothing else that I have changed.

**Comment by jacobtomlinson** [comment]
Why avoid installing?

Can you paste the file into here.

**Comment by gunhansancar** [comment]
I thought it will consume my time unnecessarily.
I found the root cause of the problem that I encountered.
I've used prose.io to edit files online.
It seems that when I commit changes by using prose.io then it clears the date field in the layout metadata of the post file.

**Comment by jacobtomlinson** [comment]
You will probably have an easier time developing software if you install the tools you require locally, including a text editor.

**Comment by gunhansancar** [comment]
Yes you are right :+1:  But I am not developing just want to blog :) So I tried to keep it simple. I wanna just add blog posts directly without any fussing, so not gonna add or change the plugins, styles etc etc :) 

Thanks anyway, really nice theme (I looked after the categories though.)
