### ISSUE TITLE
Numbered lists displaying as bulleted ones

### ISSUE THREAD

**Issue by radumas** [jacobtomlinson/carte-noire#24]
Love the template. Just having some issues with making lists, a favourite pass-time.

Your example has lists coded in markdown as:

``` markdown
### There are lists, too

  * Apples
  * Oranges
  * Potatoes
  * Milk

  1. Mow the lawn
  2. Feed the dog
  3. Dance
```

However this [displays as](http://carte-noire.jacobtomlinson.co.uk/jekyll/2014/06/10/carte-noire-in-action/)
![selection_001](https://cloud.githubusercontent.com/assets/10623872/8914099/9fa09e4c-3473-11e5-9d86-a632b44a73a6.png)

**Comment by jacobtomlinson** [comment]
Thanks for raising this. I'll take a look when I get a chance.

**Comment by radumas** [comment]
The issue appears to be with redcarpet being used, since [the example](http://pixyll.com/jekyll/pixyll/2014/06/10/see-pixyll-in-action/) that inspired you for that demo is rendered with [kramdown](https://github.com/johnotander/pixyll/blob/gh-pages/_config.yml#L48). I switched to kramdown as well after getting weird issues once I included a `<div>` tag in a post

**Comment by jacobtomlinson** [comment]
Ah thanks for this. I'll do some testing and if everything seems ok I'll switch the project to kramdown.

**Comment by jacobtomlinson** [comment]
@radumas this is rather odd. I've tried switching to kramdown and I'm still getting the same issue. Before I go diving in do you remember changing anything else?

**Comment by jacobtomlinson** [comment]
Poke @radumas

**Comment by radumas** [comment]
Hi! 

Sorry! So I changed the following in the config.yml

```
markdown: kramdown
highlighter: pygments
kramdown: 
    input: GFM
```

And then I think lists should work if typed normally. I did have an issue initially because kramdown takes a different format for lists.
