### ISSUE TITLE
Markdown stripped in post.excerpt

### ISSUE THREAD

**Issue by radumas** [jacobtomlinson/carte-noire#27]
I had a link in the first 30 words of a post (referencing a previous post), so when I scrolled to the bottom of another post to the **Read More** section I saw the following.

![selection_003](https://cloud.githubusercontent.com/assets/10623872/9012612/c67f698c-378c-11e5-83ed-85afe0cd8821.png)

My solution was to include the following in `_layouts/post.html`

``` liquid
<div class="excerpt">
             {% if post.summary %}
              {{ post.summary | strip_html | truncatewords:30 }}
             {% else %}
              {{ post.excerpt | strip_html | truncatewords:30 }}
             {% endif %}
            <a href="{{ site.baseurl }}{{ post.url }}">Continue Reading</a>
</div>
```

So that users can write a _text-only_ summary in the front-matter of the post, which will be displayed instead of the html-stripped excerpt. Thoughts?

**Comment by jacobtomlinson** [comment]
Looks great. Why don't you raise a pull request?
