### ISSUE TITLE
Text highlighting for plaintext code blocks

### ISSUE THREAD

**Issue by nulltrope** [jacobtomlinson/carte-noire#32]
When highlighting code blocks with the "text" lexer for plaintext, the highlight color is not consistent. 
Believe this is something to do with your highlightjs.piperita.scss file.

**Comment by jacobtomlinson** [comment]
Thanks for this. A screenshot would be really useful too.

**Comment by nulltrope** [comment]
![capture](https://cloud.githubusercontent.com/assets/12895773/9172928/c1d53000-3f44-11e5-85b1-e6743b5f1ad7.PNG)

Here's a snip of the code I've tried highlighting using "text" lexer. 
Instead of consistent color it comes out with some strange colors.

**Comment by jacobtomlinson** [comment]
Awesome that really helps. I'll try and look into it soon.

Out of curiosity what happens if you try and use the `shell` lexer?

**Comment by nulltrope** [comment]
I tried using the shell lexer once and the Github page build failed, figured it wasn't supported?

**Comment by jacobtomlinson** [comment]
Ok thanks.

**Comment by jacobtomlinson** [comment]
This is a bug in [highlight.js](https://highlightjs.org/) which can be fixed by increasing the version.
