### ISSUE TITLE
"more..." link on home page doesn't work for custom domains

### ISSUE THREAD

**Issue by ssundarraj** [jacobtomlinson/carte-noire#41]
http://ssundarraj.me/blog/

The "more..." link should go to http://ssundarraj.me/blog/posts, but it goes to http://ssundarraj.me/posts.

**Comment by jacobtomlinson** [comment]
I fixed this as part of `v0.2.0` just this morning. 

Please update to the latest version and make sure your `baseurl` setting in `_config.yml` is set to `blog`.

**Comment by ssundarraj** [comment]
Thanks!
