### ISSUE TITLE
Base URL in config doesn't change menu links.

### ISSUE THREAD

**Issue by ratulotron** [jacobtomlinson/carte-noire#43]
I want my blog to be a different repo than my user page one. So I changed the base URL to `username.github.io/blog` and stored this theme in a repo named blog. While the posts work fine, the links in the side bar still use `username.github.io` as base menu. This should change according to the base URL defined in _config.yml

**Comment by jacobtomlinson** [comment]
This has already been fixed by #20. Please update to the latest version of Carte Noire.
