### ISSUE TITLE
How to add custom social urls and icons?

### ISSUE THREAD

**Issue by HanderWei** [jacobtomlinson/carte-noire#45]

**Comment by HanderWei** [comment]
I solved it!

add this `line in ~/_includes/social_links.html`

```
{% if site.xxx_link %}<a href="{{ site.xxx_link }}" target="_new"><i class="fa fa-xxx"></i></a>{% endif %}
```

use  fa-xxx icon for your special social community.

**Comment by jacobtomlinson** [comment]
Hey, thanks for opening this issue. I'm happy to build some more social networks into the theme, I just started with the ones I use. 

Let me know which networks you wanted to add and we can make them easily available to everyone.

**Comment by HanderWei** [comment]
@jacobtomlinson I am a Chinese Student. In China, we use `Weibo` (sina) just like twitter in other countries. `WeChat`  and `QQ`  was the most popular Message Communication social networks in our country.

Thanks for your theme. I love it!

**Comment by HanderWei** [comment]
@jacobtomlinson But my custom icon does not have hover effects. How to add hover effects?

**Comment by jacobtomlinson** [comment]
Have a look in the CSS and find where the hover for the other icons is defined.
