### ISSUE TITLE
How to change favicons?

### ISSUE THREAD

**Issue by HanderWei** [jacobtomlinson/carte-noire#46]
I generate my custom favicons from [http://www.favicongenerator.com/](http://www.favicongenerator.com/). Then I replace all files in `favicons`. 

But the favicons does not changed.

Any help will be highly appreciated.

My blog is [chen-wei.me](http://chen-wei.me).

**Comment by jacobtomlinson** [comment]
I see you closed the issue. Did you solve the problem?

**Comment by HanderWei** [comment]
@jacobtomlinson Cause I did not clean the cache. :-)
