### ISSUE TITLE
Hide tags icon if no tags

### ISSUE THREAD

**Issue by jacobtomlinson** [jacobtomlinson/carte-noire#5]
The tags icon still displays at the bottom of an article even if there are no tags.

**Comment by rjhilgefort** [comment]
Or just some ghosted out text in italics that reads `<none>` or something. I don't even know if I would prefer that over nothing at all- just throwing out ideas.

**Comment by jacobtomlinson** [comment]
I know what you mean. Perhaps it would be good to have a setting in `_config.yml` which allows you to choose whether they aren't there or if they show with greyed out text.
