### ISSUE TITLE
Github will change the markdown engine from "redcarpet" to "kramdown"

### ISSUE THREAD

**Issue by xEdenx** [jacobtomlinson/carte-noire#50]
> You are currently using the 'redcarpet' Markdown engine, which will not be supported on GitHub Pages after May 1st. At that time, your site will use 'kramdown' for markdown rendering instead. To suppress this warning, remove the 'markdown' setting in your site's '_config.yml' file and confirm your site renders as expected. For more information, see https://help.github.com/articles/updating-your-markdown-processor-to-kramdown.

**Comment by jacobtomlinson** [comment]
Thanks, this is being covered in #35.
