### ISSUE TITLE
blockquote too wide on smartphone

### ISSUE THREAD

**Issue by ghost** [jacobtomlinson/carte-noire#53]
On http://carte-noire.jacobtomlinson.co.uk/jekyll/2014/06/10/carte-noire-in-action/ the Lorem ipsum blockquote is too wide on my smartphone.

![screenshot_20160403-082503](https://cloud.githubusercontent.com/assets/12985251/14231120/986481e2-f977-11e5-9c35-bb7f85ae9174.png)

**Comment by jacobtomlinson** [comment]
Can you please provide details on the phone, browser and screen size so I can try to reproduce.

**Comment by ghost** [comment]
I was able to fix the bug just a second ago.

https://github.com/jacobtomlinson/carte-noire/pull/52/commits/81f15232b10b9ee764cf19d4cb733ac33f79159e

**Comment by jacobtomlinson** [comment]
Does it still display correctly on other screen sizes?

**Comment by ghost** [comment]
Tried it with a few different screen sizes with the chrome dev tools - looks good.

**Comment by jacobtomlinson** [comment]
ok great. please raise it as a pull request
