### ISSUE TITLE
Posts with 2016 data are not working.

### ISSUE THREAD

**Issue by monimarlo** [jacobtomlinson/carte-noire#63]
As the title says, if I write a post with date from 2016, it simply doesn't show anywhere in the blog.

**Comment by jacobtomlinson** [comment]
Hi, thanks for raising this.

I haven't had this issue with my blog which also uses the theme. Could you send me a link to a repository which is experiencing this issue? That way I can test it for myself.

**Comment by monimarlo** [comment]
I have just forked your repository, tried creating a post with today's date, and it doesn't work. :/

**Comment by jacobtomlinson** [comment]
I can't see any posts with todays date in your fork. Can you push your changes up so I can see them.

**Comment by jacobtomlinson** [comment]
Any update on this?

**Comment by monimarlo** [comment]
Yes, sorry I haven't been in my house. I just took one of your posts and changed the date to test it out. 

EDIT: I have tried again and now it's working. I don't know what went wrong last time. :/

**Comment by jacobtomlinson** [comment]
Did you change the date in the file and also rename the file?

**Comment by CarMoreno** [comment]
For me working today May 01, 2016.

**Comment by monimarlo** [comment]
Yes, I did both.

**Comment by jacobtomlinson** [comment]
I can't reproduce this error. I also can't see any posts in [your fork](https://github.com/monimarlo/carte-noire/tree/gh-pages/_posts) with a 2016 date on them.

Can you please make the change and push it up so I can see it. Otherwise I'm going to close this issue under "cannot reproduce".

**Comment by jacobtomlinson** [comment]
Closing, cannot reproduce and OP not responding.

**Comment by monimarlo** [comment]
@jacobtomlinson , okay, now you can check [my post](https://github.com/monimarlo/monimarlo.github.io/tree/master/_posts). It's not working atm.

Sorry for the delay, btw.

**Comment by jacobtomlinson** [comment]
It looks fine to me, I pulled your repository and ran `jekyll serve`.

![image](https://cloud.githubusercontent.com/assets/1610850/15481944/21097930-20fb-11e6-8fa1-373843624ca5.png)

![image](https://cloud.githubusercontent.com/assets/1610850/15481949/28644c14-20fb-11e6-8052-1a9a059a648d.png)

**Comment by monimarlo** [comment]
Lol, so weird. Look at the live page: http://monimarlo.github.io/

EDIT: It works when I do `jekyll serve`, but not in the live page.

**Comment by jacobtomlinson** [comment]
That is weird. Do you get any email error messaged from github?

**Comment by monimarlo** [comment]
Nope, nothing.
