### ISSUE TITLE
Table Display

### ISSUE THREAD

**Issue by radumas** [jacobtomlinson/carte-noire#65]
Love the theme, but I'm not a huge fan of the way tables display.  For example:

![selection_024](https://cloud.githubusercontent.com/assets/10623872/16048905/c2a76e8a-3223-11e6-87ed-190f918fd1f2.png)

I think some borders would be a good idea but wanted to feel out what the rest of the users of this theme thought?

**Comment by jacobtomlinson** [comment]
Looks like this is fixed by #71
