### ISSUE TITLE
Suport for Django templates code

### ISSUE THREAD

**Issue by CarMoreno** [jacobtomlinson/carte-noire#66]
I have a trouble when I write code of django templates in {% highlight %} tags. I suppose that's because django templates language begins with '{%'. Some idea how I can resolve this?. Thanks.

**Comment by jacobtomlinson** [comment]
Have you tried using markdown codeblocks instead of liquid highlight tags?

**Comment by CarMoreno** [comment]
Yes!, using Markdown codeblock works, I had not thought it. But you have replace character '%' for html name '&percent;'. Finally I edit `style.css` and the result ....
![sol](https://cloud.githubusercontent.com/assets/8607266/16342826/a76cb390-39f9-11e6-9b5a-5274e5e13d20.png)
Thanks a lot!
