### ISSUE TITLE
I couldn't make it work

### ISSUE THREAD

**Issue by enesozturk** [jacobtomlinson/carte-noire#67]
Hi Jacob, I'm just new in Jekyll, I found your theme awesome. I forked it and changed it name as 'myusername.github.io' but when I open the site I face with the 404 page. What should I do?

**Comment by enesozturk** [comment]
> [Github user pages need to be in the master branch. ](http://stackoverflow.com/questions/33282460/feeling-responsive-jekylltheme-fork-provokes-404-file-not-found-at-username)

**Comment by jacobtomlinson** [comment]
:+1:
