### ISSUE TITLE
Sticky footer on search page

### ISSUE THREAD

**Issue by jacobtomlinson** [jacobtomlinson/carte-noire#7]
The footer doesn't stick to the bottom and look a bit odd on pages like the search where the content is short.

![Imgur](http://i.imgur.com/yQqMeSl.png)

**Comment by rjhilgefort** [comment]
:+1:

Maybe not sticky... that could look equally bad on really long monitors. And, wouldn't be the same across all the other pages, which could be a bit jarring.

What about just something below the search when there are no results? To separate it from the footer until there are results (that would take up that space)

**Comment by jacobtomlinson** [comment]
Hmm I know what you mean. But if you look at the screenshot above it is showing one result and still looks weird.

Do you think margin to move it down or do you mean some filler content?

If you checkout GitHub's search page as an example they've gone for margin top and bottom.
https://github.com/search

**Comment by rjhilgefort** [comment]
:+1: I think what does it for them is the horizontal rule.

**Comment by jacobtomlinson** [comment]
Yeah you're right
