### ISSUE TITLE
Syntax highlighting and latex support has broken

### ISSUE THREAD

**Issue by jacobtomlinson** [jacobtomlinson/carte-noire#76]
Looks like syntax highlighting and latex support has broken at some point.

![image](https://cloud.githubusercontent.com/assets/1610850/20259447/f212bebc-aa4c-11e6-82af-6674ad5cbb99.png)
![image](https://cloud.githubusercontent.com/assets/1610850/20259453/fc2e0096-aa4c-11e6-8e3f-44cecbb0d5c2.png)

**Comment by matthiaslischka** [comment]
Just FYI: can't reproduce on my browsers: 
http://carte-noire.jacobtomlinson.co.uk/jekyll/2014/06/10/carte-noire-in-action/
![image](https://cloud.githubusercontent.com/assets/12046115/20265696/d33ea192-aa72-11e6-9353-dd2f41ea226b.png)
![image](https://cloud.githubusercontent.com/assets/12046115/20265715/ee1066b8-aa72-11e6-85d5-6d97ba6f63a2.png)

**Comment by jacobtomlinson** [comment]
Hmm perhaps it is an issue with my local copy then.
