### ISSUE TITLE
How to add a Google Ad Word？

### ISSUE THREAD

**Issue by sxm5220** [jacobtomlinson/carte-noire#79]

**Comment by jacobtomlinson** [comment]
Please add more detail

**Comment by sxm5220** [comment]
Hope you can add Google Ad Word for this blog, I want to learn to add method, because I added but without success！

_config.yml
#this is my google ad word
google_ad_slot: 8759608812
google_ad_client: ca-pub-9882771134185440

footer.html
<div align="center">
      <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
      <ins class="adsbygoogle"
           style="display:block"
           data-ad-client="{{ site.google_ad_client }}"
           data-ad-slot="{{ site.google_ad_slot }}"
           data-ad-format="auto"></ins>
      <script>
      (adsbygoogle = window.adsbygoogle || []).push({});
      </script>
    </div>


this is url
https://github.com/sxm5220/sxm5220.github.io
Please help me!!
