### ISSUE TITLE
How do I update my copy of this theme?

### ISSUE THREAD

**Issue by sathley** [jacobtomlinson/carte-noire#80]
So I began by forking this theme. Then I added some posts and pushed it to my GitHub account. How do I get the newest features/fixes from this repo into my site?

PS: Sorry for the noob question!

**Comment by jacobtomlinson** [comment]
You can [add a new upstream](https://help.github.com/articles/configuring-a-remote-for-a-fork/) pointing to this repo and then [sync it](https://help.github.com/articles/syncing-a-fork/).
