### ISSUE TITLE
Add images

### ISSUE THREAD

**Issue by totovr** [jacobtomlinson/carte-noire#85]
Hello! I'm trying to display some pictures in the posts but I don't know why is not showing nothing

``` html
<img src="Assets/RSJ1.JPG" width="600">
```

**Comment by matthiaslischka** [comment]
I use the markdown syntax for this

```markdown
![alt text]({{"/Assets/RSJ1.JPG"}})
```

**Comment by totovr** [comment]
Also I change the syntax for this one
``` Markdown
<img src="name_of_the_user.io//assets/RSJ/RSJ1.JPG" width="600">
```
and is working, thanks!
