### ISSUE TITLE
permission to modify or edit theme contents given in license

### ISSUE THREAD

**Issue by leela52452** [jacobtomlinson/carte-noire#91]
hello @jacobtomlinson 

i have forked your theme on [gitlab](https://gitlab.com/jekyll-themes/carte-noire)

my forked [repo](https://gitlab.com/leela52452/leela52452.gitlab.io/tree/master) 

i want to modify config.yml to suit my needs, however [LICENSE](https://gitlab.com/leela52452/leela52452.gitlab.io/blob/master/LICENSE) requires your permission. can you please provide permission to **modify** `config.yml`, **delete** `_data,  _drafts & _posts`

i will retain your GPL theme license as it is.

**Comment by jacobtomlinson** [comment]
Thanks for raising this and for taking the time to read the license, I wrote that 5 years ago and you are the first person to ask. I had not intended things to be quite that strict, the license is originally from my blog where I wanted to protect the copyright on my content but not the theme.

I will update the license to make more sense, but in the meantime, I give permission for your request above.

**Comment by jacobtomlinson** [comment]
Updated. Hopefully that makes more sense.
