### ISSUE TITLE
Broken CSS

### ISSUE THREAD

**Issue by leela52452** [jacobtomlinson/carte-noire#92]
gitlab complained about removing jekyll gem when i run ci. i have updated gemfile
`gem 'jekyll', '3.8.0'
gem 'redcarpet' 
gem 'liquid', '4.0'`

somehow it broke theme and it shows in grey see `https://leela52452.gitlab.io/`

please excuse.

thank you

**Comment by jacobtomlinson** [comment]
This doesn't seem to be related to the gem or gitlab. 

It looks like [you have the baseurl set to `carte-noire/`](https://gitlab.com/leela52452/leela52452.gitlab.io/blob/master/_config.yml#L5) which is causing the page to look for the CSS at the wrong url. 

Try setting the baseurl to `/`.

**Comment by leela52452** [comment]
setting the baseurl to `" "` resolved the issue
