### ISSUE TITLE
Hamburger menu covers up post title

### ISSUE THREAD

**Issue by yochaigal** [jacobtomlinson/carte-noire#95]
I'm experiencing this issue with especially long titles (see image):

![menu](https://user-images.githubusercontent.com/817479/72622477-4bf81c00-3911-11ea-9dd1-37a6c47f85f2.png)

Is this something I can fix with padding, or what? 
Thanks for a great theme/platform for my blog btw.

**Comment by jacobtomlinson** [comment]
That's strange there should be some padding at the top to avoid this. Have you modified the theme at all?

**Comment by yochaigal** [comment]
Sure, but only to add a Home option in the hamburger menu, and to add some padding (30px) to the space between the gravatar image and the title. I've reversed these changes but the issue persists.

**Comment by yochaigal** [comment]
I fixed it by adding
      <h1 class="header" itemprop="name" style="padding-left: 30px;"" >{{ page.title }}</h1>

To my post.html.
